version: '3.8'

services:
  gateway:
    build: .
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network